sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs-v3
  - iojs-v2
  - 4.0
  - 0.12
  - 0.11
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
script:
  - npm run test
  - npm run coverage
  - npm run coverage:check
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
  - npm run coverage:push:codecov
  - npm run coverage:push:coveralls
