'use strict';

module.exports = {
  API_KEY_ENV_VAR: 'RAGAMINTS_FLICKR_API_KEY',
  API_SECRET_ENV_VAR: 'RAGAMINTS_FLICKR_API_SECRET',
  OAUTH_TOKEN_ENV_VAR: 'RAGAMINTS_FLICKR_OAUTH_TOKEN',
  OAUTH_TOKEN_SECRET_ENV_VAR: 'RAGAMINTS_FLICKR_OAUTH_TOKEN_SECRET',
  USER_NAME_ENV_VAR: 'RAGAMINTS_FLICKR_USER_NAME',
  USER_ID_ENV_VAR: 'RAGAMINTS_FLICKR_USER_ID',

  API_KEY_CLI_OPTION: 'flickr-api-key',
  API_SECRET_CLI_OPTION: 'flickr-api-secret',
  OAUTH_TOKEN_CLI_OPTION: 'flickr-oauth-token',
  OAUTH_TOKEN_SECRET_CLI_OPTION: 'flickr-oauth-token-secret',
  USER_NAME_CLI_OPTION: 'flickr-user-name',
  USER_ID_CLI_OPTION: 'flickr-user-id'
};
