'use strict';

module.exports = {
  API_KEY_ENV_VAR: 'RAGAMINTS_FLICKR_API_KEY',
  API_SECRET_ENV_VAR: 'RAGAMINTS_FLICKR_API_SECRET',
  OAUTH_TOKEN_ENV_VAR: 'RAGAMINTS_FLICKR_OAUTH_TOKEN',
  OAUTH_TOKEN_SECRET_ENV_VAR: 'RAGAMINTS_FLICKR_OAUTH_TOKEN_SECRET'
};
