'use strict';

module.exports = {
  SOFTWARE: 'ragamints',
  ERROR_PREFIX: 'ragamints: ',
  ACCESS_TOKEN_ENV_VAR: 'RAGAMINTS_ACCESS_TOKEN',
  FLICKR_API_KEY_ENV_VAR: 'RAGAMINTS_FLICKR_API_KEY',
  FLICKR_API_SECRET_ENV_VAR: 'RAGAMINTS_FLICKR_API_SECRET'
};
